  - name: set apache2 to display server ip on server 1
    shell: "echo \"<h3>This is server-01.Ip: $(hostname -f)</h3>\" > /var/www/html/index.html"
    when: inventory_hostname in groups['server_1']

  - name: set apache2 to display server ip on server 2
    shell: "echo \"<h3>This is server-02. Ip: $(hostname -f)</h3>\" > /var/www/html/index.html"
    when: inventory_hostname in groups['server_2']

  - name: set apache2 to display server ip on server 3
    shell: "echo \"<h3>This is server-3. Ip: $(hostname -f)</h3>\" > /var/www/html/index.html"
    when: inventory_hostname in groups['server_3']