---
- name: Setup Web Server
  hosts: web_servers
  remote_user: ubuntu
  become: yes
  vars_files:
    - ./vars/vars.yml

  roles:
  - apache2
  - timezone

  tasks:
  - name: deploy html page on servers
    import_tasks: tasks/main.yml
